name: Validate servers JSON against schema

on:
  pull_request:
    branches:
      - main  # Only PRs targeting main branch

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install validator
        run: npm i -D ajv-cli ajv-formats

      - name: Validate JSON files
        run: |
          shopt -s nullglob globstar
          files=(partners/servers/*.json)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No JSON files found under partners/servers/"
            exit 0
          fi

          echo "Found ${#files[@]} JSON files to validate"
          
          # Loop through each file and validate individually
          for file in "${files[@]}"; do
            echo "Validating: $file"
            if ! npx ajv validate \
              -s schemas/config.schema.json \
              -d "$file" \
              --all-errors --errors=line; then
              echo "❌ Validation failed for: $file"
              exit 1
            else
              echo "✅ Validation passed for: $file"
            fi
          done
          
          echo "All JSON files validated successfully!"